name: ci
on:
  pull_request:
  push:
    branches:
    - master
    - dev
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        rust-toolchain: [stable, nightly]
    steps:

    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        profile: minimal
        override: true

    - name: Basic build
      run: cargo build --verbose

    - name: Build docs
      run: cargo doc --verbose

    - name: Run full test suite
      run: cargo test --tests

  rustfmt:
    name: rustfmt
    runs-on: windows-2019
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Check formatting
      run: |
        cargo fmt --all -- --check