name: ci
on:
  pull_request:
  push:
    branches:
    - master
    - dev
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        rust-toolchain: [stable, nightly, 1.45.0]
        include:
          - os: ubuntu-latest
            rust-toolchain: stable

    steps:

    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        profile: minimal
        override: true

    - name: Basic build
      run: cargo build --verbose

    - name: Build docs
      run: cargo doc --verbose

# Be sure the debugger tests DO NOT run in parallel.
# Each test attaches a debugger to the test process so there
# can not be another debugger attached to the current test process.
    - name: Run debugger_test test suite
      run: cargo test --package debugger_test -- --test-threads=1
    - name: Run debugger_test_parser test suite
      run: cargo test --package debugger_test_parser --manifest-path debugger_test_parser/Cargo.toml

  rustfmt:
    name: rustfmt
    runs-on: windows-2019
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Check formatting
      run: |
        cargo fmt --all -- --check
