name: ci
on:
  pull_request:
  push:
    branches:
    - master
    - dev
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        rust-toolchain: [stable, nightly, 1.45.0]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        profile: minimal
        override: true

    - name: Basic build
      run: cargo build

# Be sure the debugger tests DO NOT run in parallel.
# Each test attaches a debugger to the test process so there
# can not be another debugger attached to the current test process.
    - name: Run debugger_test_parser test suite
      run: cargo test --package debugger_test_parser --manifest-path debugger_test_parser/Cargo.toml

    - name: Run debugger_test test suite
      run: cargo test --package debugger_test -- --test-threads=1 --nocapture

  rustfmt:
    name: rustfmt
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Check formatting
      run: |
        cargo fmt --all -- --check
